In [1]:
!python tta_submit.py

seed : 20
batch_size 64
TTA submit
transform [Resize(always_apply=False, p=1, height=344, width=344, interpolation=1)]
num_test : 32
(2000, 2)
2000
[0 0 0 ... 1 1 0]
make!!
transform [Resize(always_apply=False, p=1, height=344, width=344, interpolation=1), VerticalFlip(always_apply=False, p=1)]
num_test : 32
(2000, 2)
2000
[0 0 0 ... 1 1 0]
make!!
transform [Resize(always_apply=False, p=1, height=344, width=344, interpolation=1), HorizontalFlip(always_apply=False, p=1)]
num_test : 32
(2000, 2)
2000
[0 0 0 ... 1 1 0]
make!!
done


In [2]:
import pandas as pd
import numpy as np

final = pd.read_csv('result/m1oVH_m2oH_tta_image_size_320_cos_test.csv', header=None) # m1OVH_m2OH, m1 : full
m1oVH = pd.read_csv('result/m1oVH_tta_image_size_320_cos_full_test.csv', header=None) # m1OVH
prev = pd.read_csv('result/oVH_tta_image_size_320_cos/14test.csv', header=None) # 이전 제출
prev_real = pd.read_csv('result/m1oVH_tta_image_size_320_cos_test.csv', header=None) # 이전 제출 real

final = np.asarray(final.loc[0])
m1oVH = np.asarray(m1oVH.loc[0])
prev = np.asarray(prev.loc[0])
prev_real = np.asarray(prev_real.loc[0])

In [4]:
np.sum(final != m1oVH), np.sum(final != prev_real), np.sum(final != prev)

(11, 22, 57)